### ISSUE TITLE
Your (v)snprintf is not standard compliant

### ISSUE THREAD

**Issue by Volker-Weissmann** [libesmtp/libESMTP#18]
Quote from your source:
```C
int vsnprintf (char *str, size_t count, const char *fmt, va_list args)
{
  str[0] = 0;
  dopr(str, count, fmt, args);
  return(strlen(str));
}
```
But the [C99 standard](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf) states that 
```
The snprintf function returns the number of characters that would have been written
had n been sufficiently large, not counting the terminating null character, or a negative
value if an encoding error occurred.
```
For example ```snprintf(ar, 1, "abc")``` returns 1 when using your implementation and 3 when using a standard compliant implementation.
Also, the C99 standard states that 
```
If n is zero, nothing is written,
and s may be a null pointer.
```
but ```snprintf(NULL, 0, "abc")``` Segfaults when using your implementation.

**Comment by libesmtp** [comment]
This applies to an unsupported release of libESMTP.  Please upgrade to v1.1.0, master or the head of the libesmtp-1.1 branch.

The source file  (snprintf.c authored 1995, last modified in 2002) was removed as obsolete along with some other replacement functions. GNU autotools or meson would have been unlikely to compile/link it in any case since vsnprintf() is widely available nowadays.
```
Date:   Wed Mar 4 10:23:19 2020 +0000

    Minor tidy - provide a clean base for further development
    
    * remove snprintf() replacement, surely all modern systems are good?
    * remove getaddrinfo() replacement, in POSIX.1-2001, bind9 and lwres
    * always build with SASL support
    * remove HAVE_CONFIG_H wrappers, config.h is always included
    * add strftime() based rfc2822date()
```
